#
# SPDX-License-Identifier: Apache-2.0
#

version: "2.1"

networks:
  carbonAccounting:

services:
  chaincode-utilityemissions1:
    container_name: chaincode-utilityemissions1.carbonAccounting.com
    image: krybalko/utilityemissions-chaincode:0.0.3
    environment:
      - CHAINCODE_CCID=utilityemissions:c8db00b6daf1a14ced04a233533127e0ae3cd127b121248b2d6873f4eeec66df
      - CHAINCODE_ADDRESS=0.0.0.0:9998
    ports:
      - "9998:9998"
