#
# SPDX-License-Identifier: Apache-2.0
#

version: "2.1"

networks:
  carbonAccounting:

services:
  chaincode-utilityemissions1:
    container_name: chaincode-utilityemissions1.carbonAccounting.com
    image: krybalko/utilityemissions-chaincode:0.0.4
    environment:
      - CHAINCODE_CCID=utilityemissions:bb4f78512603de4516fcf952e444de9bbf04ea87baef3c1add3d01c51c432b40
      - CHAINCODE_ADDRESS=0.0.0.0:9998
    ports:
      - "9998:9998"
