#
# SPDX-License-Identifier: Apache-2.0
#

version: "2.1"

networks:
  carbonAccounting:

services:
  chaincode-utilityemissions2:
    container_name: chaincode-utilityemissions2.carbonAccounting.com
    image: krybalko/utilityemissions-chaincode:0.0.4
    environment:
      - CHAINCODE_CCID=utilityemissions:85f9f6d3f418309d5a7f12b50ac779b14dde60f62330ef7f7faf7c8be5bdbd33
      - CHAINCODE_ADDRESS=0.0.0.0:9999
    ports:
      - "9999:9999"
