#
# SPDX-License-Identifier: Apache-2.0
#

version: "2.1"

networks:
  carbonAccounting:

services:
  chaincode-utilityemissions2:
    container_name: chaincode-utilityemissions2.carbonAccounting.com
    image: krybalko/utilityemissions-chaincode:0.0.3
    environment:
      - CHAINCODE_CCID=utilityemissions:4eb6ceb329694c62c47e138b512706e74341f249e7633e0d7c99bd77defc4120
      - CHAINCODE_ADDRESS=0.0.0.0:9999
    ports:
      - "9999:9999"
