#
# SPDX-License-Identifier: Apache-2.0
#

version: "2.1"

networks:
  carbonAccounting:

services:
  chaincode-emissions1:
    container_name: chaincode-emissions1.carbonAccounting.com
    image: zzocker20/emissions-chaincode:0.0.6
    environment:
      - CHAINCODE_CCID=emissions:b7da638fdad84f463798742c0f6a50d166a81add7a639f836448aa5b24943075
      - CHAINCODE_ADDRESS=0.0.0.0:9998
    ports:
      - "9998:9998"
  chaincode-datalock1:
    container_name: chaincode-datalock1.carbonAccounting.com
    image: zzocker20/datalock-chaincode:0.0.1
    environment:
      - CHAINCODE_ID=datalock:f2d63aff7ab14d9845dfc1252ee6269b99d8f34d960c65832b823f4a6c8f5578
      - CHAINCODE_ADDRESS=0.0.0.0:9988
      - DATALOCK_LOG_LEVEL=DEBUG
