name: "Test Report"
on: # Run this workflow after the CI has completed
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results # Read the test-results artifact and generate an HTML report
          name: Test Report
          path: "test-results.json"
          reporter: mocha-json
